### ISSUE TITLE
Release new package on PyPi

### ISSUE THREAD

**Issue by hiaselhans** [pyqtconsole/pyqtconsole#65]
Hi maintainers,

thanks for the great package!
I've seen a recent release (1.2.2) but i can't seem to find it on pypi.
Can you actually publish a release there? should we use gh-actions to publish releases in the future?

Thanks!

**Comment by RobertoRoos** [comment]
Yeah, hadn't realised at the time I needed to do more. It's being taken care of in #66

**Comment by coldfix** [comment]
1.2.2 is released now.

**Comment by hiaselhans** [comment]
Great, thank you!!
